{"level":"error","message":"Erreur lors de la génération du dump SQL","stack":["SynchronizationService"],"timestamp":"2025-07-16T09:05:25.692Z"}
{"context":"SynchronizationService","level":"error","message":"Error: Command failed: pg_dump -h localhost -p 5432 -U postgres -d postgres -F p -f dump.sql\n'pg_dump' n'est pas reconnu en tant que commande interne\r\nou externe, un programme ex�cutable ou un fichier de commandes.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:414:12)\n    at ChildProcess.emit (node:events:524:28)\n    at maybeClose (node:internal/child_process:1101:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)","stack":["Error: Command failed: pg_dump -h localhost -p 5432 -U postgres -d postgres -F p -f dump.sql\n'pg_dump' n'est pas reconnu en tant que commande interne\r\nou externe, un programme ex�cutable ou un fichier de commandes.\r\n\n    at genericNodeError (node:internal/errors:983:15)\n    at wrappedFn (node:internal/errors:537:14)\n    at ChildProcess.exithandler (node:child_process:414:12)\n    at ChildProcess.emit (node:events:524:28)\n    at maybeClose (node:internal/child_process:1101:16)\n    at ChildProcess._handle.onexit (node:internal/child_process:304:5)"],"timestamp":"2025-07-16T09:05:25.702Z"}
